name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest

    - name: Download NLTK resources
      run: |
        python -m nltk.downloader punkt_tab wordnet averaged_perceptron_tagger averaged_perceptron_tagger_eng

    - name: Run tests
      run: pytest tests/
